### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by blerude** [ckelley324/bwa-u4-feature-request#1]
Please modify your doc so that those with the link can have access to it. As of now, I cannot view it or give you feedback. Thanks!

**Comment by ckelley324** [comment]
I did give anyone access who has a link.  I even added you manually after you sent the request.  I'm not sure why it's not working.  I'll try again.

**Comment by ckelley324** [comment]
I updated it again.  I think it was set for my business domain.  I apologize for the trouble.

**Comment by blerude** [comment]
No worries! Feedback below...

Grade: Exceeds Expectations

Great job writing up this proposal for your new and very pertinent Jammming feature. The idea itself is a natural suggestion, as most users would likely assume the Enter key would serve that purpose and therefore would find it inconvenient that the app doesn’t do that, as you yourself did. Your implementation is also the easiest way to accomplish the goal and you laid out a clean and clear course of action. I think using keyDown vs. keyPress, while important in some features, would ultimately result in the same thing here. 

I don't have much feedback on the idea you proposed because it is a rather simple feature. I am not sure if this would work, but an even simpler solution would be to see if you can catch the 'enter' key and initiate the search in the onChange function (not sure if this works because I don't know if pressing 'enter' would quite trigger a change). Your idea enhances usability of an existing feature, which is important. Moving forward, I’d think about ideas that also add entirely new features as well. For example, what if you could listen to a sample of each song returned by a query? Just an idea to bring the app to a new level, if you're looking for more of a challenge. Overall, great job identifying a way to make the app more intuitive to the user and coming up with a solution, and I hope that you follow through and implement the feature!

**Comment by ckelley324** [comment]
Thank you! I actually did implement that, and ironically, I added a preview link as well.  You can check it out here: http://ckelleyjammming.surge.sh.
